export const animalList = [
    {
        letter: 'a',
        animal: 'Alpaca',
        image: 'img_a.svg',
        sound: 'alpaca.mp3',
    },
    {
        letter: 'b',
        animal: 'Bear',
        image: 'img_b.svg',
        sound: 'bear.mp3',
    },
    {
        letter: 'c',
        animal: 'Cow',
        image: 'img_c.svg',
        sound: 'cow.mp3',
    },
    {
        letter: 'd',
        animal: 'Deer',
        image: 'img_d.svg',
        sound: 'deer.mp3',
    },
    {
        letter: 'e',
        animal: 'Elephant',
        image: 'img_e.svg',
        sound: 'elephant.mp3',
    },
    {
        letter: 'f',
        animal: 'Fox',
        image: 'img_f.svg',
        sound: 'fox.mp3',
    },
    {
        letter: 'g',
        animal: 'Giraffe',
        image: 'img_g.svg',
        sound: 'giraffe.mp3',
    },
    {
        letter: 'h',
        animal: 'Hedgehog',
        image: 'img_h.svg',
        sound: 'hedgehog.mp3',
    },
    {
        letter: 'i',
        animal: 'Iguana',
        image: 'img_i.svg',
        sound: 'iguana.mp3',
    },
    {
        letter: 'j',
        animal: 'Jellyfish',
        image: 'img_j.svg',
        sound: 'jellyfish.mp3',
    },
    {
        letter: 'k',
        animal: 'Koala',
        image: 'img_k.svg',
        sound: 'koala.mp3',
    },
    {
        letter: 'l',
        animal: 'Lion',
        image: 'img_l.svg',
        sound: 'lion.mp3',
    },
    {
        letter: 'm',
        animal: 'Monkey',
        image: 'img_m.svg',
        sound: 'monkey.mp3',
    },
    {
        letter: 'n',
        animal: 'Nightengale',
        image: 'img_n.svg',
        sound: 'nightengale.mp3',
    },
    {
        letter: 'o',
        animal: 'Opossum',
        image: 'img_o.svg',
        sound: 'opossum.mp3',
    },
    {
        letter: 'p',
        animal: 'Panda',
        image: 'img_p.svg',
        sound: 'panda.mp3',
    },
    {
        letter: 'q',
        animal: 'Qual',
        image: 'img_q.svg',
        sound: 'quail.mp3',
    },
    {
        letter: 'r',
        animal: 'Raccoon',
        image: 'img_r.svg',
        sound: 'raccoon.mp3',
    },
    {
        letter: 's',
        animal: 'Squirrel',
        image: 'img_s.svg',
        sound: 'squirrel.mp3',
    },
    {
        letter: 't',
        animal: 'Tiger',
        image: 'img_t.svg',
        sound: 'tiger.mp3',
    },
    {
        letter: 'u',
        animal: 'Unicorn',
        image: 'img_u.svg',
        sound: 'unicorn.mp3',
    },
    {
        letter: 'v',
        animal: 'Vulture',
        image: 'img_v.svg',
        sound: 'vulture.mp3',
    },
    {
        letter: 'w',
        animal: 'Wolf',
        image: 'img_w.svg',
        sound: 'wolf.mp3',
    },
    {
        letter: 'x',
        animal: 'X-Ray Fish',
        image: 'img_x.svg',
        sound: 'x-ray-fish.mp3',
    },
    {
        letter: 'y',
        animal: 'Yak',
        image: 'img_y.svg',
        sound: 'yak.mp3',
    },
    {
        letter: 'z',
        animal: 'Zebra',
        image: 'img_z.svg',
        sound: 'zebra.mp3',
    },
];
